### ISSUE TITLE
Thank you for your solutions!

### ISSUE THREAD

**Issue by zerlinwang** [dariokonopatzki/Deep-Learning-Foundations-and-Concepts-Solutions#1]
Thank you for your solutions, which helps me a lot.

Now I am reading the chapter 20 diffusion models and I encounter some problems regarding excercises.

The official solutions are not released, aren't they?

I would pay attention to this repository constantly.

Again, thank you for your sharing!

**Comment by dariokonopatzki** [comment]
Hi Zilin, 
I am glad that you find the solutions useful and I appreciate the positive feedback.
As far as I am aware, no official solutions were released at this point. Scrolling down on [BishopBook.com](https://www.bishopbook.com/) it says that solutions are 'coming soon'.
