### ISSUE TITLE
Help on Homework!

### ISSUE THREAD

**Issue by MarkKing123** [dariokonopatzki/Deep-Learning-Foundations-and-Concepts-Solutions#2]
Hi, I am a student, and I have two questions from my professor, and I don't have any clue. Could you please show me how it works? It's exercise 14.4, 19.2 Really appreciate that!

**Comment by dariokonopatzki** [comment]
Hi Mark,
Both of these exercises can be solved using transformation of densities. To solve 14.4, you need to find the inverse of an indefinite integral. This procedure is described in section 14.1.2 of the book, which also has an example.
For 19.2, you start with the transformation formula and then make use of the fact that the distribution of epsilon is Gaussian, and that you know what the Gaussian density looks like.

**Comment by MarkKing123** [comment]
Thank you so much!
