### ISSUE TITLE
About how you wrote the solutions

### ISSUE THREAD

**Issue by everydaylucky** [dariokonopatzki/Deep-Learning-Foundations-and-Concepts-Solutions#3]
I'm really happy to see you publish your solution. The formulas in your PDF are very nice, I am also planning to learn the book. How did you do it? Did you use latex? Can you give me some guidance? Thank you!

**Comment by Anderson111-maker** [comment]
Hello,thanks for your solution.Do you think the exercise of 12.3 is wrong? I

**Comment by dariokonopatzki** [comment]
Hi,
Thank you for the positive feedback.
I use a pretty minimal LaTeX template similar to the ones you can find [here](https://www.overleaf.com/latex/templates/tagged/math).
